### ISSUE TITLE
With hub baseUrl not set, jupyterhub with istio is working fine. However with hub baseUrl set ("jupyterhubtd"), user login has 500 Redirect loop detected.

### ISSUE THREAD

**Issue by cf250024** [splunk/jupyterhub-istio-proxy#39]
I was experimenting and following the blog with this proxy image to integrate jupyterhub and istio. 
It works with pods in jhub namespace injected with sidecar. The jupyter are working for user login and notebook queries.

However, when I move one step forward by setting hub baseUrl to "jupyterhubtd", I got the error message when user login: 500 : Internal Server Error Redirect loop detected." The user pod is spawned and in running 2/2. Even though the user pod is running but browser has 302 status code. I believe this is the issue of configuration. 

I checked that all the virtual services are created and Route seems correct to me: 
For example: "Prefix:  /jupyterhubtd" and "Host:  hub.jhub.svc.cluster.local" for hub service.

Also not sure for the purpose of "VIRTUAL_SERVICE_PREFIX"?
I am using jupyterhub-istio-proxy:0.0.2. I also tested with **jupyterhub-istio-proxy:0.1.1** and it seems not solving the issue.

**Comment by cf250024** [comment]
1. The fix is "Prefix: /jupyterhubtd**/hub**" and "Host: hub.jhub.svc.cluster.local" for hub service.
2. (nitpick) "VIRTUAL_SERVICE_PREFIX" is a bit confusing since prefix is used in spec as well. Virtual service name prefix is easy to understand.

**Comment by harsimranmaan** [comment]
@cf250024 it is a fair point. Do you want to introduce the new var with the same meaning and update the doc refs?
