### ISSUE TITLE
definitive way of implementation

### ISSUE THREAD

**Issue by tonymills** [splunk/jupyterhub-istio-proxy#43]
Hi all

sorry if i missed something here, but i followed the documentation provided in the link:-

https://medium.com/swlh/running-jupyterhub-with-istio-service-mesh-on-kubernetes-a-troubleshooting-journey-707039f36a7b

and at the bottom of the page it says that i have to patch kubespawner, and a link to a PR which puts a service in front of the spawned pod, i dont know if i no longer need to use this for jupyterhub with istio or there is some other way of deploying that i am not aware of? 

any help much appreciated 

Thanks in advance

Tony

**Comment by harsimranmaan** [comment]
Hi Tony, The patch was needed with the jupyterhub version at the time and is likely needed now too unless that functionality is available out of the box now. Here is a working version of JH with istio that I had prepared for my talk at ServicemeshCon. https://github.com/harsimranmaan/servicemeshcon2020/tree/main/jh-patch. The project has a working version of JH with this proxy.

**Comment by tonymills** [comment]
harsimran, 

you are a gentleman :) 

If we ever meet i owe you a beer! lol 

thanks very much
